In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [3]:
print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [5]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [4]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
## Matrizes

matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
## Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [8]:
print('Maximo', notas.max())
print('Minimo', notas.min())
print('Desvio padrão', notas.std())
print('Media', notas.mean())

Maximo 9.8
Minimo 5.6
Desvio padrão 1.5628179676469045
Media 7.76
